name: 'Read package.json version'
description: 'Output version numbers with package.json'
inputs:
  path:
    description: 'Path of package.json'
    default: 'package.json'
outputs:
  version:
    description: "Version of package"
runs:
  using: 'node12'
  main: 'lib/main.js'
