name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci

    - name: Unit Test
      run: npm test

    - name: Local action test
      uses: ./
      id: version

    - name: Get version
      run: echo "Version is  ${{ steps.version.outputs.version }}"
